### PR TITLE
Full parameterized tests support

### LINKED ISSUE #427: Add full support for parametrized tests
### Environment

1. `node -v`: v11.10.0
2. `npm -v`: 6.7.0
3. `npm ls jest`: └── jest@24.1.0 
4. Operating system: macOS Mojave

### Prerequisite
- are you able to run jest test from command line? yes
- how do you run your tests from command line? (for example: `npm run test` or `node_modules/.bin/jest`) `npm test`

### Expected Behavior

When using syntax `test.each(table)(name, fn, timeout)` [described here](https://jestjs.io/docs/en/api.html#1-testeachtable-name-fn-timeout) test status circles show the status of tests and failed test error appears in-line.

### Actual Behavior

When using syntax `test.each(table)(name, fn, timeout)` test status circles are not shown and test errors are not displayed inline.

### Workaround
If applying parametrization to `describe` with `describe.each`, test status information seems to be showed correctly.

In the image below all three tests should have been marked as failed. As it can be seen, the second does not show any test status information and the third (workaround) seems to work. Since I don't want to wrap all my separate tests into `describe.each` workaround is not that useful in my case.

screenshot 2019-02-25 at 10 34 51

### PR DESCRIPTION
**Pull request by connectdotz**
This PR adds full parameterized test support across the extension:

## test-matching
  - upgrade to the [jest-editor-support@28.1](https://github.com/jest-community/jest-editor-support/releases/tag/v28.1.0) to pick up the parser fix for full parameterized test syntax support 
  - the matching logic is enhanced to handle parameterized describe blocks, in addition to parameterized test blocks. All parameterized test results are exposed to the rest of the system.
  - 
## decorators 
  - all flavor of parameterized tests should show (computed) test status in the gutter
  - all parameterized test errors will be marked with decorators, therefore, a parameterized test block might have multiple error decorators or a single line might have multiple error messages.
  - 
## diagnosis
  - all parameterized test errors show up in the PROBLEMS area as well as hovering messages. Each with the full test name.
 
## debug
  - If there are multiple debuggable tests for the given test block, DebugCodeLens display the number of debuggable tests and will ask the user to choose which test to debug.
  - run-test command API change (backward compatible)
  - optimization: remove stop/start the internal jest tests process during debugging. (see the open question below)

## Open Questions
- I was surprised to see that we stop and restart jest process in `JestExt.runTest`. Looks like this logic was there since runTest is introduced (#172). Could not see any discussion about why that was needed... Concern that it could be a very expensive overhead especially for large projects. I tried without stop/start logic and all seem fine. So I figure unless we knew the explicit use case to justify the overhead, it is better to leave them out... 

## Notes
- There is a known issue in jest that parameterized tests have incorrect locations (facebook/jest#10412). The fix (facebook/jest#10413) was merged in [jest-26.5.0](https://github.com/facebook/jest/releases/tag/v26.5.0). Therefore, the minimal jest version for projects with parameterized tests should be >= 26.5.0 
- to eat our own dog food, I have added a few parameterized tests in our own test suites. You can build the extension with this PR to try out.
- This PR does touch quite a few files, but most are not too complicated. I have tested this for a couple of days, but more tests especially from different platforms will be needed. Hopefully, we can release this soon so more people can help testing it.
---

fixes #427 (see [comments](https://github.com/jest-community/vscode-jest/issues/427#issuecomment-760886768))

### CODE REVIEW

**Comment by connectdotz** [comment]
@CzBuCHi looks like you wrote the original debugger support (#172), if you have some time, would be great for you to review this PR as we do have some question about the stop/restart the jest process in `JestExt.runTest`

@stephtr would love to have you review this PR as well.

**Comment by CzBuCHi** [comment]
Not sure if i can help - i deleted my fork when it got merged and totally forget about it ...

about jest restarting via JestExt.runTest: probably because i didnt know any better ...

**Comment by connectdotz** [comment]
@CzBuCHi thanks for the reply.

**Comment by connectdotz** [comment]
@stephtr looks like you are busy... 

I ran with this PR last week, and it seems solid, pretty handy actually, as I started to add more parameterized tests... At this point, I think it's probably better to merge it and cut an alpha release so we can start the field testing/fixing cycle sooner... thoughts?

File: src/DebugCodeLens/DebugCodeLens.ts [hunk 1]
```diff
@@ -1,19 +1,30 @@
...
   readonly document: vscode.TextDocument;
 
+  /**
+   *
+   * @param document
+   * @param range
+   * @param fileName
+   * @param testIds test name/pattern.
+   *  Because a test block can have multiple test results, such as for paramertized tests (i.e. test.each/describe.each), there could be multiple debuggable candidates, thus it takes multiple test identifiers.
+   *  Noite: If a test id is a string array, it should represent the hierarchiical relationship of a test structure, such as [describe-id, test-id].
```
Comment (stephtr) [inline src/DebugCodeLens/DebugCodeLens.ts:17]: Typos ("Noite", "hierarchiical")

File: src/DebugCodeLens/DebugCodeLensProvider.ts [hunk 2]
```diff
@@ -67,16 +70,16 @@ export class DebugCodeLensProvider implements vscode.CodeLensProvider {
   ): vscode.ProviderResult<vscode.CodeLens> {
     if (codeLens instanceof DebugCodeLens) {
       codeLens.command = {
-        arguments: [codeLens.document, codeLens.fileName, escapeRegExp(codeLens.testName)],
+        arguments: [codeLens.document, codeLens.fileName, ...codeLens.testIds],
         command: `${extensionName}.run-test`,
-        title: 'Debug',
+        title: codeLens.testIds.length > 1 ? `Debug(${codeLens.testIds.length})` : 'Debug',
```
Comment (stephtr) [inline src/DebugCodeLens/DebugCodeLensProvider.ts:75]: Let's add a space after "Debug"?

File: src/JestExt.ts [hunk 3]
```diff
@@ -297,19 +308,43 @@ export class JestExt {
...
+      typeof id === 'string' ? id : testIdString(type, id);
+    const selectTest = async (
+      testIdentifiers: DebugTestIdentifier[]
+    ): Promise<DebugTestIdentifier | undefined> => {
+      const items: RunTestPickItem[] = testIdentifiers.map((id) => ({
+        label: idString('display-reverse', id),
+        id,
+      }));
+      const selected = await vscode.window.showQuickPick<RunTestPickItem>(items, {
+        placeHolder: 'select a test to debug',
```
Comment (stephtr) [inline src/JestExt.ts:323]: How about an uppercase "Select"?

**Review by stephtr — COMMENTED** [review]
Sorry for the delay
I had just a quick shallow look at it and tested v4 alpha 3, great work! 😃

File: src/DebugCodeLens/DebugCodeLensProvider.ts (hunk 2 above)
Comment (stephtr) [reply src/DebugCodeLens/DebugCodeLensProvider.ts:75]: Is "Debug n failing tests"/"Debug failing test" too long?

**Comment by connectdotz** [comment]
@stephtr better late than never 😉  ... I will address those in another PR
